In [1]:
def fib(n):
    if(n<1):
        return -1
    elif(n==1):
        return (0)
    elif(n==2):
        return 1
    return(fib(n-1)+fib(n-2))

def fibsum(n):
    if(n==0):
        return 0
    return(fib(n)+fibsum(n-1))


print(fib(4),fibsum(4))

2 4


In [30]:
import numpy as np
def pro(a1,a2):
    a3=[[0]*len(a2[0])]*len(a1)
    
    print(a3)
    for i in range (len(a1)):
        for j in range(len(a2[0])):
            for k in range(len(a2)):
                a3[i][j]+= (a1[i][k] * a2[k][j])
        
    print(a3)
a1=[[12,7,3],[4,5,6],[7,8,9]]
a2=[[5,8,1,2],[6,7,3,0],[4,5,9,1]]
pro(a1,a2)
print(np.dot(a1,a2))

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
[[307, 414, 245, 64], [307, 414, 245, 64], [307, 414, 245, 64]]
[[114 160  60  27]
 [ 74  97  73  14]
 [119 157 112  23]]
